# Module manifest for module 'OnlyHuman.Text'
# Generated by: Tom A. Vibeto
# Generated on: 09.08.2019
@{
	RootModule        = 'bin\Debug\netstandard2.0\OnlyHuman.Text.dll'
	ModuleVersion     = '0.0.1'
	GUID              = '8707fce4-44b8-4642-8437-b4d935731bc7'
	Author            = 'Tom A. Vibeto'
	CompanyName       = 'OnlyHuman'
	Copyright         = '(c) OnlyHuman. All rights reserved.'
	Description       = 'Various text-formatting tools.'
	PowerShellVersion = '6.0.0'
	FunctionsToExport = @()
	CmdletsToExport   = @('Join-Lines')
	VariablesToExport = '*'
	AliasesToExport   = @()
	PrivateData       = @{
		PSData = @{
		}
	}
}
